# Generated by Django 5.2.3 on 2025-06-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_application_options_alter_jobposting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('worker', 'Worker')], default='worker', max_length=10),
        ),
    ]
