# Generated by Django 5.2.3 on 2025-06-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='jobposting',
            name='api_jobpost_status_dfa092_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobposting',
            name='api_jobpost_posted__97d36a_idx',
        ),
    ]
