# Generated by Django 5.2.3 on 2025-06-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-created_at']},
        ),
    ]
