# Generated by Django 5.2.3 on 2025-06-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_jobposting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
